site_name: AquiferX
site_description: Documentation for the AquiferX Groundwater Data Visualization App
site_author: Norm Jones
copyright: Copyright &copy; 2025 Norman L. Jones
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
extra_css:
  - css/custom.css
plugins:
  - search
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Overview: overview.md
  - Preparing Data: data-preparation.md
  - Managing Data: managing-data.md
  - Viewing Data: viewing-data.md
  - Trend Analysis: trend-analysis.md
  - Spatial Analysis:
    - Overview: spatial/index.md
    - Interpolation Methods: spatial/interpolation.md
    - Raster Visualization: spatial/raster.md
    - Storage Analysis: spatial/storage.md
    - Cross Section: spatial/cross-section.md
    - Active Wells: spatial/active-wells.md
  - Imputing Data Gaps: imputation.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md
